export const AUTH_ERROR_CODES = {
  ALG_MISMATCH: "AUTH_ALG_MISMATCH",
  CHAIN_NOT_ALLOWED: "AUTH_CHAIN_NOT_ALLOWED",
  CLOCK_DRIFT: "AUTH_CLOCK_DRIFT",
  CONTEXT_REQUIRED: "AUTH_CONTEXT_REQUIRED",
  DEPENDENCY_INTEGRITY_FAILURE: "AUTH_DEPENDENCY_INTEGRITY_FAILURE",
  DUPLICATE_KID: "AUTH_DUPLICATE_KID",
  INVALID_EXPIRES_IN: "AUTH_INVALID_EXPIRES_IN",
  INVALID_KEY_PROVIDER: "AUTH_INVALID_KEY_PROVIDER",
  INVALID_RSA_KEY: "AUTH_INVALID_RSA_KEY",
  JWT_KEYS_INVALID: "AUTH_JWT_KEYS_INVALID",
  JWT_KEYS_MISSING: "AUTH_JWT_KEYS_MISSING",
  JWT_MISSING_KID: "AUTH_JWT_MISSING_KID",
  NO_PRIVATE_KEY: "AUTH_NO_PRIVATE_KEY",
  NO_SIGNING_KEY: "AUTH_NO_SIGNING_KEY",
  PUBLIC_KEY_NOT_FOUND: "AUTH_PUBLIC_KEY_NOT_FOUND",
  REDIS_CONFIG_ASSERTION_FAILED: "AUTH_REDIS_CONFIG_ASSERTION_FAILED",
  REDIS_NONCE_ERROR: "AUTH_REDIS_NONCE_ERROR",
  REDIS_REPLICATION_ASSERTION_FAILED: "AUTH_REDIS_REPLICATION_ASSERTION_FAILED",
  REDIS_REVOCATION_ERROR: "AUTH_REDIS_REVOCATION_ERROR",
  REFRESH_CONFLICT: "AUTH_REFRESH_CONFLICT",
  REFRESH_EXPIRED: "AUTH_REFRESH_EXPIRED",
  REFRESH_NOT_FOUND: "AUTH_REFRESH_NOT_FOUND",
  REFRESH_REVOKED: "AUTH_REFRESH_REVOKED",
  REVOKE_PRIMARY_FORBIDDEN: "AUTH_REVOKE_PRIMARY_FORBIDDEN",
  ROTATION_NOT_SUPPORTED: "AUTH_ROTATION_NOT_SUPPORTED",
  SIWE_DOMAIN_MISMATCH: "AUTH_SIWE_DOMAIN_MISMATCH",
  SIWE_EXPIRED: "AUTH_SIWE_EXPIRED",
  SIWE_INVALID_SIG: "AUTH_SIWE_INVALID_SIG",
  SIWE_NONCE_REPLAY: "AUTH_SIWE_NONCE_REPLAY",
  SIWE_PARSE_ERROR: "AUTH_SIWE_PARSE_ERROR",
  SIWE_TIME_DRIFT: "AUTH_SIWE_TIME_DRIFT",
  STORES_MISSING: "AUTH_STORES_MISSING",
  TIME_HISTORICAL_DRIFT: "AUTH_TIME_HISTORICAL_DRIFT",
  TIME_JUMP: "AUTH_TIME_JUMP",
  TIME_REGRESSION: "AUTH_TIME_REGRESSION",
  TIME_SOURCE_UNAVAILABLE: "AUTH_TIME_SOURCE_UNAVAILABLE",
  TOKEN_CONTEXT_MISMATCH: "AUTH_TOKEN_CONTEXT_MISMATCH",
  TOKEN_INVALID: "AUTH_TOKEN_INVALID",
  TOKEN_INVALID_SUB: "AUTH_TOKEN_INVALID_SUB",
  TOKEN_MALFORMED: "AUTH_TOKEN_MALFORMED",
  TOKEN_REVOKED: "AUTH_TOKEN_REVOKED",
} as const;

export const RPC_ERROR_CODES = {
  DEPTH_EXCEEDED: "RPC_DEPTH_EXCEEDED",
  INVALID_PAYLOAD: "RPC_INVALID_PAYLOAD",
  MAX_RETRIES: "RPC_MAX_RETRIES",
  NO_ENDPOINTS: "RPC_NO_ENDPOINTS",
  NOT_READY: "RPC_NOT_READY",
  PAYLOAD_TOO_LARGE: "RPC_PAYLOAD_TOO_LARGE",
  VALIDATION_ERROR: "RPC_VALIDATION_ERROR",
  PROVIDER_ERROR: "RPC_PROVIDER_ERROR",
  TIMEOUT: "RPC_TIMEOUT",
  ALL_PROVIDERS_FAILED: "RPC_ALL_PROVIDERS_FAILED",
} as const;

export const CONFIG_ERROR_CODES = {
  INVALID: "CONFIG_INVALID",
  INMEMORY_STORES_IN_PRODUCTION: "CONFIG_INMEMORY_STORES_IN_PRODUCTION",
} as const;

export const SECURITY_ERROR_CODES = {
  INVALID_PARAM: "SECURITY_INVALID_PARAM",
  SECRET_LEAK: "SECURITY_SECRET_LEAK",
  UNAUTHORIZED_ORIGIN: "SECURITY_UNAUTHORIZED_ORIGIN",
  INSECURE_DEFAULT: "SECURITY_INSECURE_DEFAULT",
} as const;

export const PLUGIN_ERROR_CODES = {
  DUPLICATE: "PLUGIN_DUPLICATE",
  INVALID: "PLUGIN_INVALID",
} as const;

export const STORAGE_ERROR_CODES = {
  GET_FAILED: "STORAGE_GET_FAILED",
  PINATA_JWT_MISSING: "STORAGE_PINATA_JWT_MISSING",
  PUT_BAD_RESPONSE: "STORAGE_PUT_BAD_RESPONSE",
  PUT_FAILED: "STORAGE_PUT_FAILED",
} as const;

export const TABLELAND_ERROR_CODES = {
  KEY_MISSING: "TABLELAND_KEY_MISSING",
  QUERY_ERROR: "TABLELAND_QUERY_ERROR",
} as const;

export const CERAMIC_ERROR_CODES = {
  CONFIG_MISSING: "CERAMIC_CONFIG_MISSING",
} as const;

export const AI_ERROR_CODES = {
  CLIENT_NOT_INITIALIZED: "AI_CLIENT_NOT_INITIALIZED",
  CONFIG_MISSING: "AI_CONFIG_MISSING",
  TOOL_UNKNOWN: "AI_TOOL_UNKNOWN",
} as const;

export const CRYPTO_ERROR_CODES = {
  DECRYPT_ERROR: "CRYPTO_DECRYPT_ERROR",
  KEY_INVALID: "CRYPTO_KEY_INVALID",
} as const;

export const REALTIME_ERROR_CODES = {
  NOT_CONNECTED: "REALTIME_NOT_CONNECTED",
} as const;

export const TX_ERROR_CODES = {
  RECEIPT_TIMEOUT: "TX_RECEIPT_TIMEOUT",
} as const;

export const AA_ERROR_CODES = {
  NONCE_FAILED: "AA_NONCE_FAILED",
  SIMULATION_FAILED: "AA_SIMULATION_FAILED",
  PAYMASTER_INVALID_RESPONSE: "AA_PAYMASTER_INVALID_RESPONSE",
  BUNDLER_RPC_ERROR: "AA_BUNDLER_RPC_ERROR",
} as const;

export const CIRCUIT_ERROR_CODES = {
  OPEN: "CIRCUIT_OPEN",
} as const;
